import { describe, expect, it } from "bun:test";
import { mkdirSync, readFileSync, rmSync } from "node:fs";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Database } from "bun:sqlite";
import { emitRedirects } from "$pipeline/stages/emit-redirects";
import { buildRelationshipDDL } from "$pipeline/relationships/relationship-graph";

describe("emitRedirects", () => {
  it("writes a Cloudflare _redirects file from entity_redirects", () => {
    const root = mkdtempSync(join(tmpdir(), "ardenfall-redirects-"));
    try {
      const dbPath = join(root, "data.sqlite");
      const db = new Database(dbPath);
      db.exec(buildRelationshipDDL());
      db.run(
        `INSERT INTO entity_nodes (entity_type, entity_id, label, route_path, canonical_slug, short_id, is_public)
         VALUES ('item', 'item-a', 'Iron Sword', '/items/iron-sword--4ed20218', 'iron-sword--4ed20218', '4ed20218', 1)`,
      );
      db.run(
        `INSERT INTO entity_redirects (source_type, source_id, target_type, target_id, reason)
         VALUES ('item-route', '/items/4ed202185a05d98439595e3fcab021c8.11400000', 'item', 'item-a', 'legacy-id')`,
      );
      db.run(
        `INSERT INTO entity_redirects (source_type, source_id, target_type, target_id, reason)
         VALUES ('item-route', '/items/old-name--4ed20218', 'item', 'item-a', 'name-changed')`,
      );
      db.close();

      mkdirSync(join(root, "static"), { recursive: true });
      const out = emitRedirects({ sqlitePath: dbPath, outputDir: join(root, "static") });

      expect(out.count).toBe(2);
      const body = readFileSync(join(root, "static", "_redirects"), "utf8");
      expect(body).toContain(
        "/items/4ed202185a05d98439595e3fcab021c8.11400000 /items/iron-sword--4ed20218 301",
      );
      expect(body).toContain("/items/old-name--4ed20218 /items/iron-sword--4ed20218 301");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it("writes a header-only _redirects file when no redirects exist", () => {
    const root = mkdtempSync(join(tmpdir(), "ardenfall-empty-redirects-"));
    try {
      const dbPath = join(root, "data.sqlite");
      const db = new Database(dbPath);
      db.exec(buildRelationshipDDL());
      db.close();

      mkdirSync(join(root, "static"), { recursive: true });
      const out = emitRedirects({ sqlitePath: dbPath, outputDir: join(root, "static") });

      expect(out.count).toBe(0);
      expect(readFileSync(out.filePath, "utf8")).toBe("# Generated by ardenfall-compendium.\n");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});
