import { describe, expect, it } from "bun:test";
import { Database } from "bun:sqlite";
import { mkdirSync, readFileSync, rmSync } from "node:fs";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { emitRedirects } from "$pipeline/stages/emit-redirects";
import { ENTITY_GRAPH_DDL } from "$pipeline/relationships/relationship-graph";
import type { EntityDescriptor } from "$pipeline/types";
import type { LoadDescriptorsOutput } from "$pipeline/stages/load-descriptors";

function descriptors(...entities: EntityDescriptor[]): LoadDescriptorsOutput {
  return {
    entities: Object.fromEntries(entities.map((entity) => [entity.id, entity])),
    variants: {},
  };
}

function entity(id: string, route: string, previousRoutes?: string[]): EntityDescriptor {
  return {
    id,
    kind: id === "npc" ? "instance" : "definition",
    label: { singular: id, plural: `${id}s` },
    extraction: { source: "record", root: "fixture" },
    canonicalTable: `${id}s`,
    fields: [{ name: "id", type: "id", from: "id" }],
    site: previousRoutes ? { route, previousRoutes } : { route },
  };
}

function makeDatabase(root: string, nodes: string[] = []): string {
  const dbPath = join(root, "data.sqlite");
  const db = new Database(dbPath);
  db.exec(ENTITY_GRAPH_DDL);
  for (const node of nodes) db.run(node);
  db.close();
  return dbPath;
}

function readRedirects(
  dbPath: string,
  outputDir: string,
  descriptorSet: LoadDescriptorsOutput,
): { count: number; body: string } {
  mkdirSync(outputDir, { recursive: true });
  const output = emitRedirects({ sqlitePath: dbPath, outputDir, descriptors: descriptorSet });
  return { count: output.count, body: readFileSync(output.filePath, "utf8") };
}

describe("emitRedirects", () => {
  it("emits a splat and a base redirect for a retired route base", () => {
    const root = mkdtempSync(join(tmpdir(), "ardenfall-retired-redirects-"));
    try {
      const dbPath = makeDatabase(root, [
        `INSERT INTO entity_nodes
          (entity_type, entity_id, label, display_label, route_path, canonical_slug, short_id, has_page)
         VALUES ('npc', 'npc-a', 'Ada', 'Ada', '/characters/ada--11111111', 'ada--11111111', '11111111', 1)`,
      ]);
      const result = readRedirects(
        dbPath,
        join(root, "static"),
        descriptors(entity("npc", "/characters", ["/placed-characters"])),
      );

      expect(result.count).toBe(2);
      expect(result.body).toBe(
        [
          "# Generated by ardenfall-compendium.",
          "/placed-characters/* /characters/:splat 301",
          "/placed-characters /characters 301",
          "",
        ].join("\n"),
      );
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it("emits exact page redirects when another family reuses the old base", () => {
    const root = mkdtempSync(join(tmpdir(), "ardenfall-reused-redirects-"));
    try {
      const dbPath = makeDatabase(root, [
        `INSERT INTO entity_nodes
          (entity_type, entity_id, label, display_label, route_path, canonical_slug, short_id, has_page)
         VALUES
          ('character', 'character-a', 'Darvaki', 'Darvaki', '/character-types/darvaki--22222222', 'darvaki--22222222', '22222222', 1),
          ('character', 'character-b', 'Karu Elf', 'Karu Elf', '/character-types/karu-elf--33333333', 'karu-elf--33333333', '33333333', 1),
          ('character', 'character-template', 'Template', 'Template', NULL, 'template--44444444', '44444444', 0)`,
      ]);
      const result = readRedirects(
        dbPath,
        join(root, "static"),
        descriptors(
          entity("npc", "/characters"),
          entity("character", "/character-types", ["/characters"]),
        ),
      );

      expect(result.count).toBe(2);
      expect(result.body).toContain(
        "/characters/darvaki--22222222 /character-types/darvaki--22222222 301",
      );
      expect(result.body).toContain(
        "/characters/karu-elf--33333333 /character-types/karu-elf--33333333 301",
      );
      expect(result.body).not.toContain("/characters/*");
      expect(result.body).not.toContain("/characters /character-types");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it("emits no redirects for a family without previous routes", () => {
    const root = mkdtempSync(join(tmpdir(), "ardenfall-empty-redirects-"));
    try {
      const dbPath = makeDatabase(root);
      const result = readRedirects(
        dbPath,
        join(root, "static"),
        descriptors(entity("npc", "/characters")),
      );

      expect(result.count).toBe(0);
      expect(result.body).toBe("# Generated by ardenfall-compendium.\n");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});
