#!/usr/bin/env bun
import standaloneCode from "ajv/dist/standalone";
import Ajv2020 from "ajv/dist/2020";
import addFormats from "ajv-formats";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

const targets = [
  { schema: "schemas/entity.schema.json", out: "pipeline/dist/validate-entity.mjs" },
  { schema: "schemas/variant.schema.json", out: "pipeline/dist/validate-variant.mjs" },
  { schema: "schemas/manifest.schema.json", out: "pipeline/dist/validate-manifest.mjs" },
  { schema: "schemas/snapshot.schema.json", out: "pipeline/dist/validate-snapshot.mjs" },
  {
    schema: "schemas/asset-manifest.schema.json",
    out: "pipeline/dist/validate-asset-manifest.mjs",
  },
  {
    schema: "schemas/artifact-manifest.schema.json",
    out: "pipeline/dist/validate-artifact-manifest.mjs",
  },
  { schema: "schemas/diagnostics.schema.json", out: "pipeline/dist/validate-diagnostics.mjs" },
  { schema: "schemas/digest.schema.json", out: "pipeline/dist/validate-digest.mjs" },
  {
    schema: "schemas/fixture-manifest.schema.json",
    out: "pipeline/dist/validate-fixture-manifest.mjs",
  },
  {
    schema: "schemas/master-tooltip.schema.json",
    out: "pipeline/dist/validate-master-tooltip.mjs",
  },
];

// Single Ajv instance so $ref between schemas resolves.
const ajv = new Ajv2020({ code: { source: true, esm: true }, allErrors: true });
addFormats(ajv);

// Pre-load every schema so cross-schema $ref works.
for (const { schema } of targets) {
  const doc = JSON.parse(readFileSync(schema, "utf8"));
  ajv.addSchema(doc);
}

// Shared `.d.ts` shape; matches Ajv 8's runtime ValidateFunction surface.
const declarationBody = `// Auto-generated by pipeline/scripts/codegen-validators.ts. Do not edit.
export interface AjvValidationError {
  instancePath: string;
  schemaPath: string;
  keyword: string;
  params: Record<string, unknown>;
  message?: string;
}
export interface AjvValidateFunction {
  (data: unknown): boolean;
  errors?: AjvValidationError[] | null;
}
declare const validate: AjvValidateFunction;
export default validate;
`;

for (const { schema, out } of targets) {
  const doc = JSON.parse(readFileSync(schema, "utf8"));
  const validate = ajv.getSchema(doc.$id) ?? ajv.compile(doc);
  const code = standaloneCode(ajv, validate);
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, code);
  // Emit a sibling .d.mts so TypeScript can resolve types when consumers
  // `import validate from "./validate-entity.mjs"`.
  const dtsOut = out.replace(/\.mjs$/, ".d.mts");
  writeFileSync(dtsOut, declarationBody);
  console.warn(`wrote ${out} + ${dtsOut}`);
}
