#!/usr/bin/env bun
import standaloneCode from "ajv/dist/standalone";
import Ajv2020 from "ajv/dist/2020";
import addFormats from "ajv-formats";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

const targets = [
  { schema: "schemas/entity.schema.json", out: "pipeline/dist/validate-entity.mjs" },
  { schema: "schemas/variant.schema.json", out: "pipeline/dist/validate-variant.mjs" },
  { schema: "schemas/manifest.schema.json", out: "pipeline/dist/validate-manifest.mjs" },
  { schema: "schemas/snapshot.schema.json", out: "pipeline/dist/validate-snapshot.mjs" },
  {
    schema: "schemas/asset-manifest.schema.json",
    out: "pipeline/dist/validate-asset-manifest.mjs",
  },
  {
    schema: "schemas/artifact-manifest.schema.json",
    out: "pipeline/dist/validate-artifact-manifest.mjs",
  },
  { schema: "schemas/diagnostics.schema.json", out: "pipeline/dist/validate-diagnostics.mjs" },
  { schema: "schemas/digest.schema.json", out: "pipeline/dist/validate-digest.mjs" },
  {
    schema: "schemas/fixture-manifest.schema.json",
    out: "pipeline/dist/validate-fixture-manifest.mjs",
  },
  {
    schema: "schemas/master-tooltip.schema.json",
    out: "pipeline/dist/validate-master-tooltip.mjs",
  },
  {
    schema: "schemas/finalize-timings.schema.json",
    out: "pipeline/dist/validate-finalize-timings.mjs",
  },
];

const schemaDocs = targets.map(({ schema }) => JSON.parse(readFileSync(schema, "utf8")));

/**
 * One Ajv instance per target, each pre-loaded with every schema so the one
 * cross-schema reference resolves (variant.schema.json points at
 * entity.schema.json#/$defs/field).
 *
 * A shared instance would also resolve that reference, but Ajv numbers the
 * functions and schema constants it emits from a counter that lives on the
 * instance. Compiling every target through one instance therefore made each
 * generated file's contents depend on every other schema: adding a subschema to
 * entity.schema.json renumbered `validate36` to `validate38` in ten unrelated
 * validators. `check:validators` regenerates and diffs these files, so that
 * coupling turned the check into noise. Compiling one root per instance keeps
 * the numbering local to that schema and its references.
 */
function createAjv(): Ajv2020 {
  const ajv = new Ajv2020({ code: { source: true, esm: true }, allErrors: true });
  addFormats(ajv);
  for (const doc of schemaDocs) ajv.addSchema(doc);
  return ajv;
}

// Shared `.d.ts` shape; matches Ajv 8's runtime ValidateFunction surface.
const declarationBody = `// Auto-generated by pipeline/scripts/codegen-validators.ts. Do not edit.
export interface AjvValidationError {
  instancePath: string;
  schemaPath: string;
  keyword: string;
  params: Record<string, unknown>;
  message?: string;
}
export interface AjvValidateFunction {
  (data: unknown): boolean;
  errors?: AjvValidationError[] | null;
}
declare const validate: AjvValidateFunction;
export default validate;
`;

for (const { schema, out } of targets) {
  const doc = JSON.parse(readFileSync(schema, "utf8"));
  const ajv = createAjv();
  const validate = ajv.getSchema(doc.$id) ?? ajv.compile(doc);
  const code = standaloneCode(ajv, validate);
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, code);
  // Emit a sibling .d.mts so TypeScript can resolve types when consumers
  // `import validate from "./validate-entity.mjs"`.
  const dtsOut = out.replace(/\.mjs$/, ".d.mts");
  writeFileSync(dtsOut, declarationBody);
  console.warn(`wrote ${out} + ${dtsOut}`);
}
