#!/usr/bin/env bun
import { readFileSync, writeFileSync } from "node:fs";

interface DescriptorField {
  name: unknown;
}

interface Descriptor {
  id: unknown;
  fields: unknown;
}

const targets = [
  { entity: "location", typeName: "LocationFieldName", sourceTypeName: "LocationSnapshotFields" },
  { entity: "portal", typeName: "PortalFieldName", sourceTypeName: "PortalSnapshotFields" },
] as const;

function readFields(entity: string): string[] {
  const path = `entities/${entity}/entity.json`;
  let descriptor: Descriptor;
  try {
    descriptor = JSON.parse(readFileSync(path, "utf8")) as Descriptor;
  } catch (error) {
    throw new Error(`cannot read descriptor ${path}`, { cause: error });
  }
  if (descriptor.id !== entity) {
    throw new Error(`descriptor ${path} has id ${String(descriptor.id)}, expected ${entity}`);
  }
  if (!Array.isArray(descriptor.fields)) {
    throw new Error(`descriptor ${path} has no fields array`);
  }

  const names: string[] = [];
  const seen = new Set<string>();
  for (const field of descriptor.fields) {
    if (!field || typeof field !== "object" || !("name" in field)) {
      throw new Error(`descriptor ${path} has a malformed field entry`);
    }
    const name = (field as DescriptorField).name;
    if (typeof name !== "string" || !/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) {
      throw new Error(`descriptor ${path} has an invalid field name ${JSON.stringify(name)}`);
    }
    if (seen.has(name)) {
      throw new Error(`descriptor ${path} declares field ${JSON.stringify(name)} more than once`);
    }
    seen.add(name);
    names.push(name);
  }
  return names;
}

const declarations = targets.map(({ entity, typeName, sourceTypeName }) => {
  const names = readFields(entity);
  if (names.length === 0) throw new Error(`descriptor ${entity} declares no fields`);
  const valueName = `${entity.replace(/-([a-z])/g, (_, letter: string) => letter.toUpperCase())}FieldNames`;
  const tuple = names.map((name) => `  ${JSON.stringify(name)}`).join(",\n");
  return {
    entity,
    valueName,
    declaration: `import type { ${sourceTypeName} as Source${sourceTypeName} } from "../src/types.ts";\n\nexport declare const ${valueName}: readonly [\n${tuple}\n];\nexport type ${typeName} = (typeof ${valueName})[number];\nexport type ${sourceTypeName} = Pick<\n  Source${sourceTypeName},\n  Extract<${typeName}, keyof Source${sourceTypeName}>\n>;`,
    runtime: `export const ${valueName} = [${names.map((name) => JSON.stringify(name)).join(", ")}];`,
  };
});

const declaration = `// Auto-generated by pipeline/scripts/codegen-entity-fields.ts. Do not edit.\n\n${declarations.map(({ declaration }) => declaration).join("\n\n")}\n`;
const runtime = `// Auto-generated by pipeline/scripts/codegen-entity-fields.ts. Do not edit.\n\n${declarations.map(({ runtime }) => runtime).join("\n")}\n`;
writeFileSync("pipeline/dist/entity-fields.d.mts", declaration);
writeFileSync("pipeline/dist/entity-fields.mjs", runtime);
console.warn("wrote pipeline/dist/entity-fields.mjs + pipeline/dist/entity-fields.d.mts");
