import { Database } from "bun:sqlite";
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export interface EmitRedirectsInput {
  sqlitePath: string;
  outputDir: string;
}

export interface EmitRedirectsOutput {
  count: number;
  filePath: string;
}

interface RedirectRow {
  source: string;
  route: string;
}

export function emitRedirects(input: EmitRedirectsInput): EmitRedirectsOutput {
  const db = new Database(input.sqlitePath, { readonly: true });
  try {
    const rows = db
      .query<RedirectRow, []>(
        `SELECT r.source_id AS source,
                CASE
                  WHEN r.target_type = 'item' THEN '/items/' || n.canonical_slug
                  ELSE n.route_path
                END AS route
         FROM entity_redirects r
         JOIN entity_nodes n
           ON n.entity_type = r.target_type AND n.entity_id = r.target_id
         WHERE r.source_type = 'item-route' AND n.is_public = 1
         ORDER BY r.source_id`,
      )
      .all();

    mkdirSync(input.outputDir, { recursive: true });
    const filePath = join(input.outputDir, "_redirects");
    const lines = ["# Generated by ardenfall-compendium."];
    for (const row of rows) lines.push(`${row.source} ${row.route} 301`);
    writeFileSync(filePath, `${lines.join("\n")}\n`);
    return { count: rows.length, filePath };
  } finally {
    db.close();
  }
}
