import { Database } from "bun:sqlite";
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { LoadDescriptorsOutput } from "./load-descriptors.ts";

export interface EmitRedirectsInput {
  sqlitePath: string;
  outputDir: string;
  descriptors: LoadDescriptorsOutput;
}

export interface EmitRedirectsOutput {
  count: number;
  filePath: string;
}

interface PublishedNodeRow {
  entity_type: string;
  canonical_slug: string;
  route_path: string;
}

export function emitRedirects(input: EmitRedirectsInput): EmitRedirectsOutput {
  const db = new Database(input.sqlitePath, { readonly: true });
  try {
    const publishedNodes = db
      .query<PublishedNodeRow, []>(
        `SELECT entity_type, canonical_slug, route_path
         FROM entity_nodes
         WHERE has_page = 1 AND route_path IS NOT NULL
         ORDER BY entity_type, canonical_slug`,
      )
      .all();
    const nodesByEntity = new Map<string, PublishedNodeRow[]>();
    for (const node of publishedNodes) {
      const nodes = nodesByEntity.get(node.entity_type) ?? [];
      nodes.push(node);
      nodesByEntity.set(node.entity_type, nodes);
    }

    const entities = Object.values(input.descriptors.entities)
      .filter((entity) => entity.site?.previousRoutes && entity.site.previousRoutes.length > 0)
      .sort((left, right) => left.id.localeCompare(right.id));
    const currentRoutes = new Map<string, string>();
    for (const entity of Object.values(input.descriptors.entities)) {
      if (entity.site) currentRoutes.set(entity.id, entity.site.route);
    }

    const lines: string[] = ["# Generated by ardenfall-compendium."];
    for (const entity of entities) {
      const site = entity.site;
      if (!site) continue;
      const nodes = nodesByEntity.get(entity.id) ?? [];
      for (const previousBase of site.previousRoutes ?? []) {
        const reusedByAnotherFamily = [...currentRoutes].some(
          ([entityId, route]) => entityId !== entity.id && route === previousBase,
        );
        if (reusedByAnotherFamily) {
          for (const node of nodes) {
            lines.push(
              `${routeWithSegment(previousBase, node.canonical_slug)} ${node.route_path} 301`,
            );
          }
          continue;
        }

        // A retired base is safe for a splat because no current family owns it. A reused base
        // needs exact page redirects so the family now published there keeps its overview.
        if (previousBase !== site.route) {
          lines.push(`${previousBase}/* ${routeWithSegment(site.route, ":splat")} 301`);
          lines.push(`${previousBase} ${site.route} 301`);
        }
      }
    }

    mkdirSync(input.outputDir, { recursive: true });
    const filePath = join(input.outputDir, "_redirects");
    writeFileSync(filePath, `${lines.join("\n")}\n`);
    return { count: lines.length - 1, filePath };
  } finally {
    db.close();
  }
}

function routeWithSegment(base: string, segment: string): string {
  return base === "/" ? `/${segment}` : `${base}/${segment}`;
}
