<script lang="ts">
  import { browser } from "$app/environment";
  import { resolve } from "$app/paths";
  import EntityTable from "$lib/components/EntityTable.svelte";
  import type {
    ItemOverviewCategory,
    ItemOverviewFilter,
    ItemOverviewRow,
  } from "$lib/server/read-models";

  type Column = {
    id: string;
    label: string;
    field: keyof ItemOverviewRow & string;
    renderer?: "text" | "itemNameWithIcon";
    sortable: boolean;
  };

  let {
    rows,
    columns,
    categories,
    filters,
  }: {
    rows: ItemOverviewRow[];
    columns: Column[];
    categories: ItemOverviewCategory[];
    filters: ItemOverviewFilter[];
  } = $props();

  let query = $state("");
  let variant = $state("all");

  if (browser) {
    const params = new URLSearchParams(window.location.search);
    query = params.get("q") ?? "";
    variant = params.get("variant") ?? "all";
  }

  const filteredRows = $derived(
    rows.filter((row) => {
      const matchesVariant = variant === "all" || row.variant === variant;
      const term = query.trim().toLowerCase();
      const matchesQuery = term.length === 0 || (row.name ?? row.id).toLowerCase().includes(term);
      return matchesVariant && matchesQuery;
    }),
  );

  function syncUrl() {
    if (!browser) return;
    const url = new URL(window.location.href);
    if (query.trim()) url.searchParams.set("q", query.trim());
    else url.searchParams.delete("q");
    if (variant !== "all") url.searchParams.set("variant", variant);
    else url.searchParams.delete("variant");
    history.replaceState(history.state, "", `${url.pathname}${url.search}${url.hash}`);
  }
</script>

<div class="grid gap-4">
  <div
    class="border-border bg-card grid gap-3 rounded-lg border p-4 sm:grid-cols-[minmax(12rem,1fr)_minmax(12rem,16rem)]"
  >
    <label class="grid gap-1 text-sm">
      <span class="text-muted-foreground">Search</span>
      <input
        class="border-border bg-background rounded-md border px-3 py-2"
        bind:value={query}
        oninput={syncUrl}
        placeholder="Filter items"
      />
    </label>
    <label class="grid gap-1 text-sm">
      <span class="text-muted-foreground">Variant</span>
      <select
        class="border-border bg-background rounded-md border px-3 py-2"
        bind:value={variant}
        onchange={syncUrl}
      >
        <option value="all">All variants</option>
        {#each filters.find((filter) => filter.id === "variant")?.options ?? [] as option (option.value)}
          <option value={option.value}>{option.label} ({option.count})</option>
        {/each}
      </select>
    </label>
  </div>

  <nav aria-label="Item categories" class="flex flex-wrap gap-2 text-sm">
    {#each categories as category (category.id)}
      <!-- eslint-disable-next-line svelte/no-navigation-without-resolve -- category hrefs are generated by the static read model -->
      <a class="border-border hover:bg-muted rounded-full border px-3 py-1" href={category.href}
        >{category.label} ({category.itemCount})</a
      >
    {/each}
  </nav>

  <p class="text-muted-foreground text-sm">{filteredRows.length} matching items</p>
  <EntityTable
    {columns}
    rows={filteredRows}
    rowHref={(row) => resolve("/items/[id]", { id: row.id })}
  />
</div>
